antData.commonNames = {
"Acanthomyops": "citronella ant",
"Acromyrmex": "leaf-cutter ant",
"Anoplolepis gracilipes": "yellow crazy ant",
"Anoplolepis": "pugnacious ant",
"Atta cephalotes": "sauba ant",
"Atta texana": "Texas leafcutting ant",
"Atta": "leaf-cutter ant",
"Brachyponera chinensis": "Asian needle ant",
"Brachyponera": "needle ant",
"Camponotus chromaiodes": "red carpenter ant",
"Camponotus consobrinus": "banded sugar ant",
"Camponotus floridanus": "Glorida carpenter ant",
"Camponotus herculeanus": "Hercules ant",
"Camponotus pennsylvanicus": "black carpenter ant",
"Camponotus variegatus": "Hawaiian carpenter ant",
"Camponotus": "carpenter ant",
"Carebara diversa": "East Indian harvesting ant",
"Carebara": "marauder ant",
"Cephalotes borgmeieri": "gliding ant",
"Cephalotes": "turtle ant",
"Cephalotini": "turtle ant",
"Crematogaster": "acrobat ant",
"Dorylinae": "army ant",
"Dorylus": "driver ant",
"Dorymyrmex insanus": "pyramid ant",
"Dorymyrmex": "cone ant",
"Eciton burchellii": "Eciton army ant",
"Ectatomma tuberculatum": "kelep",
"Forelius pruinosus": "high noon ant",
"Formica exsectoides": "Allegheny mound ant",
"Formica fuliginosa": "jet ant",
"Formica fusca": "silky ant",
"Formica obscuripes": "Western thatching ant",
"Formica polyctena": "European red wood ant",
"Formica pratensis": "European red wood ant",
"Formica rufa": "horse ant",
"Formica sanguinea": "warrior ant",
"Formica": "wood ant",
"Formicidae": "ant",
"Formicinae": "formicine ant",
"Haidomyrmecinae": "hell ant",
"Iridomyrmex purpureus": "meat ant",
"Iridomyrmex": "rainbow ant",
"Lasius claviger": "smaller yellow ant",
"Lasius flavus": "turf ant",
"Lasius interjectus": "larger yellow ant",
"Lasius niger": "black garden ant",
"Lasius": "moisture ant",
"Lepisiota capensis": "small black sugar ant",
"Leptanillinae": "army ant",
"Linepithema humile": "Argentine ant",
"Monomorium minimum": "little black ant",
"Monomorium pharaonis": "pharaoh ant",
"Mutillidae": "velvet ant",
"Myrmecia gulosa": "red bull ant",
"Myrmecia pilosula": "jack jumper ant",
"Myrmecia": "bull ant",
"Myrmecocystus mexicanus": "honeypot ant",
"Myrmelachista schumanni": "lemon ant",
"Myrmica": "red ant",
"Nothomyrmecia": "dinosaur ant",
"Nylanderia fulva": "tawny crazy ant",
"Ochetellus glaber": "black household ant",
"Odontomachus": "trap-jaw ant",
"Oecophylla smaragdina": "green tree ant",
"Oecophylla": "weaver ant",
"Ooceraea biroi": "clonal raider ant",
"Paraponera clavata": "bullet ant",
"Paratrechina longicornis": "crazy ant",
"Pheidole megacephala": "African big-headed ant",
"Pheidole": "big-headed ant",
"Pogonomyrmex badius": "Florida harvester ant",
"Pogonomyrmex barbatus": "red harvester ant",
"Pogonomyrmex californicus": "California harvester ant",
"Pogonomyrmex maricopa": "Maricopa harvester ant",
"Pogonomyrmex occidentalis": "Western harvester ant",
"Pogonomyrmex rugosus": "rough harvester ant",
"Pogonomyrmex": "harvester ant",
"Ponerinae": "ponerine ant",
"Pseudomyrmex gracilis": "slender twig ant",
"Pseudoponera stigma": "pan-tropical panther ant",
"Pseudoponera": "panther ant",
"Solenopsis geminata": "tropical fire ant",
"Solenopsis invicta": "red imported fire ant",
"Solenopsis molesta": "thief ant",
"Solenopsis molesta": "thief ant",
"Solenopsis richteri": "black imported fire ant",
"Solenopsis xyloni": "Southern fire ant",
"Solenopsis": "fire ant",
"Tapinoma melanocephalum": "ghost ant",
"Tapinoma sessile": "odorous house ant",
"Temnothorax albipennis": "rock ant",
"Tetramorium immigrans": "pavement ant",
"Tetramorium": "pavement ant",
"Wasmannia auropunctata": "little fire ant",
"Zigrasimeciinae": "iron-maiden ants",
}