R74mojiData = {
/*"shortcode":["Full Name","closest emoji" or "",duplicate closest emoji?] */
"acne":["Face with Acne","🙁‍🔴‍🔴‍🔴"],
"adhesive_bandage":["Face with Adhesive Bandage on Forehead","😕‍🩹"],
"angle_frown":["Angle Frown :<",":<"],
"angle_smile":["Angle Smile :>",":>"],
"angry_cat_emoticon":["Angry Cat Emoticon >:3",">:3"],
"angry_demon":["Angry Demon","👺"],
"angry_imp":["Angry Imp","👿"],
"angry_shout":["Angry Shouting","😠‍😲"],
"angry":["Angry","😠"],
"angry2":["Angry with Visible Veins","😠‍💢"],
"bandana":["Face with Red Bandana",""],
"big_eyes":["Face with Big Eyes","⚫️‍➖‍⚫️"],
"big_pupils":["Face with Big Pupils","🔘‍➖‍🔘"],
"big_smile":["Face with Large Smile","🙂‍🙂"],
"bitcoin_eyes":["Face with Bitcoin Eyes","🤑‍₿️‍₿️"],
"biting_lip":["Biting Lip","🥴‍💞"],
"biting_rose":["Face with Rose in Mouth","😗‍🌹"],
"blindfolded":["Blindfolded Face","🦯‍😮"],
"bloodshot_eyes":["Face with Bloodshot Eyes","😀‍👁‍👁"],
"bloodshot_right":["Face with Bloodshot Eyes Looking Right","👀‍😀"],
"blow_kiss_wink":["Blowing Kiss and Winking","😘"],
"blow_kiss":["Blowing Kiss","😙‍❤️"],
"blowing_gum":["Blowing Bubblegum","😙‍🟣"],
"blowing_nose":["Blowing Nose with Tissue","🤧"],
"blush":["Blushing Smile","😊"],
"bracket_frown":["Bracket Frown :[",":["],
"bracket_smile":["Bracket Smile :]",":]"],
"break_up":["Face with Broken Hearts","😭‍💔‍💔‍💔"],
"broken_heart_eyes":["Face with Broken Heart Eyes","☹️‍💔‍💔"],
"floating_broken_heart":["Face with Broken Heart","😭‍💔"],
"bruised_eye":["Face with Bruised Eye","😟‍🟣‍👁"],
"brushing_teeth":["Brushing Teeth","😁‍🪥"],
"burp":["Burping Face","😮‍💨‍🟢"],
"care":["Hugging Heart","🤗‍❤️"],
"cat_emoticon":["Cat Emoticon :3",":3"],
"cat":["Cat Face","🐱"],
"clout_goggles":["Face with Clout Goggles","😎‍🔳‍◻️‍🔳"],
"clown":["Clown","🤡"],
"cold_face":["Frozen Face","🥶"],
"cold_face2":["Cold Face","😬‍🧊"],
"cold_sweat":["Cold Sweat","😰"],
"cold_sweat2":["Cold Sweat (Yellow Face)","💧‍😧"],
"covering_ears":["Face with Hands over Ears","🙂‍🙉"],
"covering_eye":["Face with Hands over Right Eye","🙂‍👁‍👁‍🤚"],
"covering_eyes":["Face with Hands over Eyes","🙂‍🙈"],
"cowboy":["Face with Cowboy Hat","🤠"],
"cracked_head":["Cracked Head","☹️‍〽️"],
"crazy_eyes":["Face with Crazy Eyes","↖️‍😀‍↘️"],
"creepy_smile":["Creepy Smile","😀‍👁‍👁"],
"cross_eyed":["Cross-Eyed Face","➡️‍😀‍⬅️"],
"cry":["Face with Tear","😢"],
"cussing":["Face with Symbols over Mouth","🤬"],
"cussing2":["Face with Symbols over Mouth (Yellow)","😠‍🤬"],
"dead_face_mask":["Dead Face with Face Mask","😵‍😷"],
"dead_ghost":["Dead Face with Ghost in Mouth","😵‍👻"],
"dead_head_bandage":["Dead Face with Head Bandages","😵‍🤕"],
"dead_nosebleed":["Dead Face with Nosebleed","😵‍👃‍🩸"],
"dead":["Dead Face","😵"],
"desolate":["Desolate Face","😨‍⚪️‍⚫️"],
"despair":["Face of Despair","😧"],
"despair2":["Face of Slight Despair","😦"],
"different_eyes":["Face with Different-Sized Eyes","⬛️‍➖‍◼️"],
"disappointed":["Disappointed Face","😞"],
"disguised":["Face with Disguise","🥸"],
"disgusted_tongue":["Disgusted Face with Tongue Out","😖‍👅"],
"disgusted":["Disgusted Face","😖"],
"dizzy_star":["Face with Revolving Star","😵‍💫‍💫"],
"dizzy":["Dizzy Face","😵‍💫"],
"drool":["Drooling Face","🤤"],
"dunce":["Face with Dunce Cap","😔‍/️‍D️‍\\️"],
"eating_pizza":["Face Eating Pizza","😋‍🍕"],
"embarassed":["Embarassed Face","😳‍➡️"],
"emo":["Face with Emo Hair","👁‍🗨‍〰️‍◼️‍⬛️"],
"envy":["Angry Envious Face","😠‍🟢"],
"epic":["Epic Face","😀‍↗️"],
"epic2":["Epic Face with Closed Mouth","🙂‍↗️"],
"euro_tongue":["Face with Euro Eyes and Tongue","🤑‍€️‍€️"],
"evil_demon":["Evil Demon","👹"],
"evil_imp":["Evil Imp","😈"],
"evil":["Evil Face","🙂‍😠"],
"exhale":["Face Exhaling","😮‍💨"],
"exploding_head":["Face with Exploding Head","🤯"],
"eyebrow_raised":["Face with Eyebrow Raised","🤨"],
"eyepatch":["Face with Eyepatch","👁‍⚫️"],
"face_mask_white":["Face with White Face Mask","😷‍⚪️"],
"face_mask":["Face with Face Mask","😷"],
"face_shield":["Face with Face Shield","😷‍🪟"],
"faceless":["Faceless Head","🟡"],
"fart":["Farting Face","😣‍💨"],
"fearful":["Fearful Face","😨"],
"fearful2":["Fearful Face (Yellow)","😨‍🟡"],
"fever":["Sweating Face with Thermometer","🥵‍🌡"],
"fire_eyes":["Face with Flaming Eyes","🙂‍🔥‍🔥"],
"flaming_face":["Dead Face on Fire","😵‍🔥"],
"flat_eyes_mouthless":["Face with Flat Eyes and No Mouth","😶‍😑"],
"flat_eyes":["Face with Flat Eyes","😑"],
"floating_question_marks":["Face with Floating Question Marks","🤨‍❔‍❔‍❔"],
"floating_star":["Face with Floating Star","😊‍⭐️"],
"flushed_inflated":["Inflated Flushed Face","😳‍😳"],
"flushed_nosebleed":["Flushed Face with Nosebleed","😳‍👃‍🩸"],
"flushed_sweating":["Sweating Flushed Face","🥵‍😳"],
"flushed":["Flushed Face","😳"],
"frown_left":["Frown Pointing Left","⬅️‍🙁"],
"frown_right":["Frown Pointing Right","🙁‍➡️"],
"frown":["Frowning Face","☹️"],
"frown2":["Slightly Frowning Face","🙁"],
"gas_mask":["Face with Gas Mask","🙂‍🥽‍🌫"],
"gasp":["Gasping Face","😱‍🟡"],
"giggle":["Giggling Face with Hand over Mouth","🤭"],
"glass_head":["Face with Glass Head","🙂‍🧠‍🪟"],
"glasses_push":["Face Pushing Glasses","😌‍👓‍👈"],
"glasses":["Face with Glasses","🙂‍👓"],
"grimace":["Grimacing Face","😬"],
"grin":["Happy Grin Face","😁"],
"grinning":["Grinning Face","😀"],
"grinning2":["Happy Grinning Face","😄"],
"halo":["Face with Halo","😇"],
"happy_cussing":["Face Cussing Happily","☺️‍🤬"],
"happy_grimace":["Happy Grimacing Face","😁‍😬"],
"happy_surprised":["Happy Surprised Face","☺️‍😲"],
"happy_tear":["Happy Face with Tear","🥲"],
"happy":["Very Happy Face","🙂‍☺️"],
"happy2":["Happy Face","🙂‍😊"],
"happy3":["Slightly Happy Face","🙂‍🙂"],
"head_bandage":["Face with Head Bandages","🤕"],
"head_in_clouds":["Face in Clouds","😶‍🌫️"],
"headphones":["Face with Headphones","🙂‍🎧"],
"heart_eyes_smile":["Smiling Face with Heart Eyes","🙂‍❤️‍❤️"],
"heart_eyes":["Face with Heart Eyes","😍"],
"heart_eyes2":["Face with Vertical Heart Eyes","😀‍❤️‍❤️"],
"hehe":["Giggling Looking Top-Right","🙄‍🤭"],
"hot_face":["Hot Face","🥵"],
"hug":["Hugging Face","🤗"],
"hush":["Shushing Face","🤫"],
"idea":["Face with Idea Lightbulb","🤔‍💡"],
"in_love":["Face with Floating Hearts","🥰"],
"inhale":["Face Inhaling Happily","💨‍😮"],
"jealous":["Frown of Jealousy","🙁‍🟢"],
"joy":["Laughing with Tears of Joy","😂"],
"kappa":["Kappa","Kappa"],
"kiss_left":["Kissing to Left","⬅️‍😚"],
"kiss_right":["Kissing to Right","😚‍➡️"],
"kiss_smile":["Kissing Smile Face","😙"],
"kiss_wink":["Kissing Winking Face","😙‍😉"],
"kiss":["Kissing Face","😚"],
"kiss2":["Calm Kissing Face","😗"],
"laughing":["Laughing Face","😆"],
"lenny":["Lenny Face","🌝"],
"love_face":["Face with Floating Heart","☺️‍❤️"],
"lul":["Laughing with Finger on Chin","👉‍😆"],
"lying":["Face with Long Nose","🤥"],
"meh":["Meh Face","😕"],
"melting_face":["Melting Face","🙂‍♨️‍☀️"],
"money_eyes":["Face with Dollar Eyes","🙂‍💲‍💲"],
"money_tongue":["Face with Dollar Eyes and Tongue","🤑"],
"monocle":["Face with Monocle","🧐"],
"moon_face":["Moon Face","🌚"],
"mouthless":["Mouthless Face","😶"],
"mustache":["Face with Mustache","🙂‍〰️"],
"nausea":["Nauseated Face","🤢"],
"nausea2":["Nauseated Face (Yellow)","🤢‍🟡"],
"nerd":["Nerd Face","🤓"],
"neutral":["Neutral Face","😐"],
"new_year_glasses":["Face with 2020 New Year Glasses","🙂‍2️⃣‍0️⃣‍2️⃣‍0️⃣"],
"ninja":["Ninja","🥷"],
"nodding_yes":["Face Nodding Yes","🙂‍↕️"],
"nose_face":["Face with Visible Nose","🙂‍👃"],
"nosebleed":["Face with Nosebleed","🙁‍👃‍🩸"],
"ok_face":["Face with OK Eyes","🙂‍🆗"],
"oops":["Surprised Face with Hand over Mouth","🫢"],
"oops2":["Slightly Surprised Face with Hand over Mouth","😲‍🤭"],
//"pacifier_old":["Face with Baby Pacifier (Old Version)","☺️‍👶"],
"pacman":["PAC-MAN","😮‍🧀‍🧀‍🧀"],
"party_hat_face":["Face with Party Hat","☺️‍🥳"],
"party_horn_face":["Face Blowing Party Horn","🥳‍💨"],
"party":["Partying Face","🥳"],
"peeking":["Face Peeking Through Hands","🫣"],
"pensive_cowboy":["Sad Cowboy","😔‍🤠"],
"pensive_flushed":["Pensive Flushed Face","😔‍😳"],
"pensive_headphones":["Pensive Face with Headphones","😔‍🎧"],
"pensive":["Pensive","😔"],
"pirate_hat":["Face with Pirate Hat","🥳‍⛵️"],
"pirate":["Pirate","🙂‍⛵️"],
"pirate2":["Pirate with Bandana","🤕‍⛵️"],
"pleading":["Pleading Face","🥺"],
"pogchamp":["Surprised Face to Right","😮‍➡️"],
"poggers":["Surprised Face to Left","⬅️‍😮"],
"pound_tongue":["Face with Pound Eyes and Tongue","🤑‍£️‍£️"],
"powercry":["Powercry Face","🥺‍🥺"],
"question_mark_eyes":["Face with Question Mark Eyes","😕‍❔‍❔"],
"question_mark_face":["Face with Floating Question Mark","🤨‍❔"],
"rage_steaming":["Angry Face Steaming","😡‍♨️"],
"rage":["Raging Face","😡"],
"rainbow_sunglasses":["Face with Rainbow Sunglasses","😎‍🌈"],
"really":["Disappointed in You face","😐‍😑"],
"relaxed":["Relaxed Face","☺️"],
"relieved":["Relieved Face","😌"],
"rofl":["Rolling on the Floor Laughing","🤣"],
"rolling_eyes_smile":["Rolling Eyes and Smiling","🙂‍🙄"],
"rolling_eyes_up":["Face with Eyes Looking Up","🙄‍⬆️"],
"rolling_eyes":["Face with Rolling Eyes","🙄"],
"running_nose":["Face with Running Nose","🙁‍👃‍💧"],
"sad_covering_ears":["Sad Face with Hands over Ears","😔‍🙉"],
"sad_face_mask":["Sad Face with Face Mask","😔‍😷"],
"sad_hug":["Sad Hugging Face","😔‍🤗"],
"sad_rage":["Half Sad Half Angry Face","😢‍😡"],
"sad_relieved":["Sad but Relieved Face","😥"],
"sad_relieved2":["Sad but Relieved Face (Blue)","😥‍😨"],
"sad_sweat":["Sad Face with Cold Sweat","😓"],
"sad":["Sad Face","😞‍😞"],
"santa_hat":["Face with Santa Hat","🙂‍🧑‍🎄"],
"santa_party":["Face with Santa Hat Partying","🥳‍🧑‍🎄"],
"santa":["Santa Claus","🎅"],
"scream":["Screaming Face","😱"],
"serious_sunglasses":["Serious Face with Sunglasses","😐‍😎"],
"shaking_no":["Face Shaking Head No","🙁‍↔️"],
"shamrock_eyes":["Face with Shamrock Eyes",""],
"shocked":["Shocked Face with Eyebrows Raised","😯"],
"shocked2":["Shocked Face","😮"],
"sick":["Face with Thermometer","🤒"],
"silly":["Winking Face with Tongue Out","😜"],
"ski_mask":["Face with Ski Mask","😶‍⬛️"],
"slash_mouth":["Slash Mouth Emoticon :/",":/"],
"sleep_deprived":["Sleep Deprived","😞‍😩"],
"sleeping_ghost":["Sleeping Face with Ghost","😴‍👻"],
"sleeping":["Sleeping Face","😴"],
"sleepy_eyes":["Face with Sleepy Eyes","😐‍😴"],
"sleepy":["Sleepy Face","😪"],
"slight_meh":["Slight Meh Face","😕‍😕"],
"slight_whistle":["Face Whistling Slightly","😯‍💨"],
"small_pupils":["Face with Small Pupils","😀‍▪️‍▪️"],
"smile_down":["Face Smiling Down","🙂‍⬇️"],
"smile_left":["Face Smiling to Left","⬅️‍🙂"],
"smile_right":["Face Smiling to Right","🙂‍➡️"],
"smile_up":["Face Smiling Up","🙂‍⬆️"],
"smile":["Smiling Face","🙂"],
"smiley":["Smiling Face with Mouth Open","😃"],
"smirk":["Smirking Face","😏"],
"smoking_cigar":["Face Smoking Cigar","😮‍🚬‍🟤"],
"smoking_pipe":["Face Smoking Pipe","😮‍🚬‍🪵"],
"smoking":["Face Smoking Cigarette","😮‍🚬"],
"smug":["Smug Face","-v-"],
"snowman":["Snowman Face","⛄️"],
"sob_clown":["Sobbing Clown","🤡‍😭"],
"sob_despair":["Sobbing Face of Despair","😧‍😭"],
"sob_party":["Sobbing Partying Face","🥳‍😭"],
"sob_sunglasses":["Sobbing Face with Sunglasses","😎‍😭"],
"sob":["Sobbing Face","😭"],
"sob2":["Sobbing Pleading Face","🥺‍😭"],
"squint_frown":["Squinting Frowning Face","😣"],
"squint_grimace":["Squinting Grimacing Face","😣‍😬"],
"squint_kiss":["Squinting Kissing Face",">3<"],
"squint_open_mouth":["Squinting Face with Mouth Open","😣‍😮"],
"squint_smile":["Squinting Smiling Face",">u<"],
"squint_tongue":["Squinting Face with Tongue Out","😝"],
"squint":["Squinting Face in Disgust","😣‍😦"],
"star_eyes":["Starstruck Face","🤩"],
"stubble":["Face with Stubble Beard","🧔‍🪒"],
"sunglasses":["Face with Sunglasses","😎"],
"surprised":["Surprised Face","😯"],
"suspicious":["Suspicious Face to Right",">.>"],
"suspicious2":["Suspicious Face to Left","<.<"],
"sweat_smile":["Smile Face with Sweat Drop","😅"],
"sweating":["Sweating Face","🥵‍🟡"],
"talking":["Talking Face with Speech Balloon","🙂‍💬"],
"tangled_lights":["Face Tangled in Holiday Lights","💡‍🙃‍💡‍💡"],
"tears_of_joy":["Face Holding Back Tears of Joy","☺️‍🥺"],
"tears_of_joy2":["Grinning Face Holding Back Tears of Joy","😄‍🥺"],
"terrified":["Terrified Face","😨‍😨‍😨"],
"thinking":["Thinking Face","🤔"],
"thonk":["Thonk Face","🤔‍🤔"],
"tiny_neutral":["Tiny Neutral Face","😐‍😐"],
"tiny_smile_blush":["Blushing Face with Tiny Smile","☺️‍🙂"],
"tired":["Tired Face","😫"],
"tongue_out":["Face with Tongue Out","😛"],
"triumph":["Face of Triumph","😤"],
"unamused":["Unamused Face","😒"],
"underwater_head":["Squinting Face Underwater","😖‍🌊"],
"upside_down_frown":["Upside-Down Frowning Face","🙁‍🙃"],
"upside_down_neutral":["Upside-Down Neutral Face","😐‍🙃"],
"upside_down":["Upside-Down Smiling Face","🙃"],
"uwu":["UwU Emoticon","UwU"],
"vomiting":["Vomiting Face","🤮"],
"vomiting2":["Vomiting Face (Yellow)","🤮‍🟡"],
"wall_eyed":["Walleyed Face","⬅️‍😀‍➡️"],
"weary":["Weary Face","😩"],
"whistling":["Face Whistling","😯‍🎶"],
"white_eyes":["Face with No Pupils","😀‍⚪️‍⚪️"],
"wide":["Wide Smiling Face","🟡‍🙂‍🟡"],
"wink_cry":["Crying Face Winking","😢‍😉"],
"wink_frown":["Frowning Face Winking","🙁‍😉"],
"wink":["Winking Face","😉"],
"woozy":["Woozy Face","🥴"],
"worried":["Worried Face","😟"],
"worried2":["Worried Face (Blue)","😟‍😨"],
"wrapped":["Gift-Wrapped Face","🎁"],
"xd":["xD Emoticon","xD"],
"xok":["Xok Face","[Xök]"],
"yawn":["Yawning Face","🥱"],
"yen_tongue":["Face with Yen Eyes and Tongue","🤑‍¥️‍¥️"],
"yum":["Smiling Face with Tongue Out","😋"],
"zany":["Zany Face","🤪"],
"zipper_mouth":["Face with Mouth Zippered Shut","🤐"],
"a_mouth":["Face with 'A' Mouth •A•","•A•"],
"anxious":["Grinning Face with Cold Sweat","😅‍😨"],
"bang_head":["Head Banging Against Brick Wall","😑‍💢‍🧱"],
"black_smiling_face":["U+263B ☻ Black Smiling Face","☻"],
"c_mouth":["Face with 'C' Mouth :c",":c"],
"coin_eyes":["Face with Coin Eyes and Dollar Tongue","🤑‍🪙‍🪙"],
"colon_d":["Reversed Face with 'D' Mouth D:","D:"],
"cross_eyed_tongue":["Cross Eyed Face with Tongue Out","🤪‍😛"],
"d_colon":["Face with 'D' Mouth :D",":D"],
"dead_mouthless":["Dead Face with No Mouth","😵‍😶"],
"dead_smile":["Dead Face Smiling","😵‍🙂"],
"dead_tongue":["Dead Face with Tongue Out","😵‍👅"],
"disappointed2":["Disappointed Face","😞‍😞"],
"dotted_face":["Dotted Face","🫥"],
"dotted_smile":["Dotted Smiling Face","🫥‍🙂"],
"earth_face":["Earth Face","🌎‍🙂"],
"earth":["Planet Earth","🌎"],
"eating":["Face Eating with Cheek Full","☺️‍😋"],
"eye_lips_eye":["Eye Lips Eye Face 👁👄👁","👁‍👄‍👁"],
"flushed_left":["Flushed Face Looking to Left","⬅️‍😳"],
"frown_emoticon":["Frowning Emoticon :(",":("],
"global_warming_face":["Earth Face on Fire","🔥‍🌎‍😵‍🔥"],
"global_warming":["Planet Earth on Fire","🔥‍🌎‍🔥"],
"happy_flowers":["Smiling Face with Flowers","🌺‍☺️‍🌸"],
"happy_flushed":["Smiling Flushed Face","😳‍☺️"],
"heart_squeeze":["Face Squeezing Heart and Squinting","😣‍🧡"],
"i_mouth":["Face with 'I' Mouth :I",":I"],
"l_mouth":["Face with 'L' Mouth :L",":L"],
"licking_lips":["Face Licking Lips","☺️‍👅"],
"lips_kiss":["Face with Red Lips Blowing Kiss","😘‍💋"],
"lips":["Face with Red Lips","🙂‍👄"],
"looking_up_tongue":["Face Looking Up with Tongue Out",""],
"mitosis":["Face Replicating via Mitosis","⬅️‍😮‍😮‍➡️"],
"moon":["Moon","🌑"],
"neutral_sob":["Sobbing Face With Eyes Straight","T-T"],
"owo":["OwO Face","OwO"],
"petrified":["White Dead Face","😵‍⚪️"],
"pig":["Pig Face","🐷"],
"rainbow_heart_eyes":["Face with Rainbow Heart Eyes","😍‍🌈"],
"replacement":["Replacement Face","[?]"],
"robot":["Robot Face","🤖"],
"s_mouth":["Face with 'S' Mouth :S",":S"],
"sad_lines":["Sad Face with Blue Lines","😓‍😨"],
"si":["Katakana Si Face ㋛","㋛"],
//"silly_old":["Winking Face with Tongue Out (Old Version)",""],
"sleeping_mask":["Face with Sleeping Mask","😴‍😴"],
"smelling_flower":["Face Smelling Flower","😤‍🌺"],
"smile_emoticon":["Smiling Emoticon :)",":)"],
"sorrow":["Face Squinting and Crying","😣‍😭"],
"drool_heart_eyes":["Drooling Face with Heart Eyes","😍‍🤤"],
"scowl":["Scowling Face","😲‍😲‍😲‍😲‍😲"],
"high":["High Face Smiling with Pink Eyes","☺️‍🔴‍🔴"],
"pink_eyes":["Frowning Face with Pink Eyes","🙁‍🔴‍🔴"],
"weed":["High Face Smoking Weed","🍁‍🚬‍😌"],
"bonk":["Flushed Face Being Hit with Hammer","😳‍🔨"],
"caveman":["Caveman Face",""],
"cyclops":["Cyclops Face","🟡‍👁"],
"ogre":["Ogre Face",""],
"vampire":["Vampire Face","🧛🏻"],
"vampire_yellow":["Vampire Face (Yellow)","🧛"],
"pumpkin":["Pumpkin","🎃‍🎃"],
"rainbow_face":["Rainbow Face Grinning","😄‍🌈"],
"jack_o_lantern":["Jack-o'-Lantern","🎃"],
"visor_glasses":["Face with Visor Glasses","😕‍😎‍😎"],
"8bit":["8-Bit Pixelized Face","🙂‍👾"],
"muppet":["Muppet Face",""],
"alien":["Alien Face","👽"],
"alien2":["Strange Alien Face","👽‍🟡"],
"bike_helmet":["Face with Bike Helmet","🙂‍🚲‍⛑"],
"man_black_hair":["Man with Black Hair","👨🏻"],
"snowy_head":["Face with Snow on Head","❄️‍❄️‍❄️‍😕‍❄️‍❄️‍❄️"],
"hiding":["Black Face with Eyes Showing","👁‍🗨‍👁‍🗨"],
"crown":["Face with Crown","🫅"],
"https":["Face with Floating Lock","🙂‍🔒"],
"rofl2":["Rolling on the Floor Laughing","🤣‍😆"],
"cat_ears":["Face with Cat Ear Headband","🙂‍🐱"],
"squint_covering_ears":["Face Squinting and Covering Ears","🙉‍😣"],
"hippie":["Hippie Face","🙂‍🌈‍✌️"],
"peace":["Face with Peace Sign Hand","🙂‍✌️"],
//"mustache_old":["Face with Mustache (Old Version)",""],
"baby":["Baby Face with Pacifier","👶"],
"stricken":["Fearful Face with Lines","〰️‍😨‍〰️"],
"suggestive":["Face Smiling and Raising Eyebrows","🙂‍🤨"],
"taped_mouth":["Face with Mouth Taped Shut","😶‍❌"],
"tu":["Katakana Tu Face ㋡","㋡"],
"ultrashock":["Old Samsung Shocked Emoji","😰‍😱‍😱"],
"v_mouth":["Face with 'V' Mouth :V",":V"],
"wavy_mouth":["Face with Wavy Mouth","•~•"],
"white_frowning_face":["U+2639 ☹ White Frowning Face",""],
"white_smiling_face":["U+263A ☺ White Smiling Face",""],
"x_mouth":["Face with 'X' Mouth :X",":X"],
"z_mouth":["Face with 'Z' Mouth :Z",":Z"],
"zany_smile":["Zany Face Smiling","🙂‍🤪"],
//"zany_old":["Zany Face (Old Version)",""],
"amazed":["Amazed Face Drooling","😮‍🤤"],
"black":["Black-Colored Smiling Face","⚫️‍🙂"],
"blue_bowtie":["Face with Blue Bowtie","👨‍💼"],
"blue":["Blue Smiling Face","🔵‍🙂"],
"bomb":["Angry Bomb Face","💣"],
"bowtie":["Face with Bowtie","👨‍💼"],
"brown":["Brown-Colored Smiling Face","🟤‍🙂"],
"cat_angry":["Angry Cat Face","😾"],
"cat_cry":["Crying Cat Face","😿"],
"cat_flushed":["Flushed  Cat Face","😺‍😳"],
"cat_grin":["Grinning Cat Face","😸"],
"cat_heart_eyes":["Cat Face with Heart Eyes","😻"],
"cat_joy":["Laughing Cat Face","😹"],
"cat_kiss":["Kissing Cat Face","😽"],
"cat_scream":["Screaming Cat Face","🙀"],
"cat_smile":["Smiling Cat Face","😺"],
"cat_smirk":["Smirking Cat Face","😼"],
"chef_hat":["Face with Chef Hat","🧑‍🍳"],
"chef":["Chef","🧑‍🍳"],
"cyan":["Cyan Smiling Face","🔵‍🙂"],
"gray":["Gray Smiling Face","⚪️‍🙂"],
"green":["Green Smiling Face","🟢‍🙂"],
"hacker":["Hacker","😈💻"],
"hear_no_evil":["Hear No Evil Monkey","🙉"],
"jester":["Jester","🃏"],
"laptop_confused":["Confused Face using Laptop","🤨‍💻"],
"laptop_rage":["Angry Face using Laptop","😡‍💻"],
"laptop":["Face using Laptop","🧑‍💻"],
"lime":["Lime Smiling Face","🟢‍🙂"],
"monkey_flushed":["Flushed Monkey Face","🐵‍😳"],
"monkey":["Monkey Face","🐵"],
"orange":["Orange Smiling Face","🟠‍🙂"],
"pink_bow":["Face with Pink Bow","🙂‍🎀"],
"purple":["Purple Smiling Face","🟣‍🙂"],
"red":["Red Smiling Face","🔴‍🙂"],
"salute":["Saluting Face","o7"],
"see_no_evil":["See No Evil Monkey","🙈"],
"skull":["Skull","💀"],
"slapped":["Face Getting Slapped","😣‍💢‍👋"],
"speak_no_evil":["Speak No Evil Monkey","🙊"],
"tone1":["Pale Smiling Face","🙂🏻"],
"tone2":["Cream White Smiling Face","🙂🏼"],
"tone3":["Moderate Brown Smiling Face","🙂🏽"],
"tone4":["Dark Brown Smiling Face","🙂🏾"],
"tone5":["Black Skinned Smiling Face","🙂🏿"],
"white":["White Smiling Face","⚪️‍🙂"],
"3d_glasses":["Face with 3D Glasses","🙂‍🟥‍➖‍🟦"],
"alien_hand":["Alien Face Doing Vulcan Salute","👽‍🖖"],
"angry_cry":["Angry Crying Face","😡‍😢"],
"arm_sneeze":["Sneezing into Arm","💪‍🤧"],
"braces":["Face with Braces","😁‍✨"],
"broken_heart_face":["Broken Heart Face","😭‍💔"],
"broken_heart":["Broken Heart","💔"],
"clap":["Face Clapping","👏"],
"dab":["Face Dabbing","\\o>"],
"down":["Face Pointing Down","👇"],
"egg_face":["Egg Face","🥚‍🙂"],
"egg":["Egg","🥚"],
"eyeless":["Face with No Eyes",")"],
"facepalm":["Face Facepalming","🤦"],
"fboy":["F-Boy","🥴‍♂️"],
"finger_guns_l":["Face with Finger Guns Pointing Left","👈‍👈‍😏"],
"finger_guns_r":["Face with Finger Guns Pointing Right","😏‍👉‍👉"],
"finger_touch":["Face Pleading and Touching Fingers","👉‍👈"],
"fingers_crossed":["Face Crossing Fingers","🤞"],
"fingers_in_ears":["Face with Fingers in Ears","👉‍😑‍👈"],
"fistbump_l":["Face Fistbumping Leftwards","🤛‍🙂"],
"fistbump_r":["Face Fistbumping Rightwards","🙂‍🤜"],
"flex":["Face Flexing Biceps","💪"],
"floating_stars":["Face with 4 Floating Stars","⭐️‍⭐️‍☺️‍⭐️‍⭐️"],
"fork_knife_2":["Hungry Face with Fork and Knife","😋‍🍴"],
"fork_knife":["Face with Fork and Knife","🙂🍴"],
"hands_folded":["Face with Folded Hands","😐‍🤝"],
"hands_interlocked":["Face with Interlocked Hands","😐‍🤝"],
"handshake_l":["Face Shaking Hand (Left)","🙂‍🫱"],
"handshake_r":["Face Shaking Hand (Right)","🫲‍🙂"],
"happy_hands":["Face with Happy Hands","🙌"],
"heart_eyes_drool":["Drooling Face with Heart Eyes","😍‍🤤"],
"heart_face":["Heart Face","❤️‍🙂"],
"heart_handshake_l":["Face Shaking Hand in Love (Left)","🙂‍🫱‍❤️"],
"heart_handshake_r":["Face Shaking Hand in Love (Right)","❤️‍🫲‍🙂"],
"heart_thought_bubble":["Face Thinking About Love","☺️‍💭‍❤️"],
"heart":["Heart","❤️"],
"ily":["Face with I Love You Hand","🤟"],
"italian_hand":["Face with Italian Hand","🤌"],
"joy_eyes":["Laughing Face with Open Eyes","😂‍👁‍👁"],
"l_hand":["Laughing Face Gesturing L","😆‍L️"],
"left_down":["Face Pointing Down Left","↙️"],
"left_right":["Face Pointing Right","👈‍👉"],
"left_up":["Face Pointing Up","↖️"],
"left":["Face Pointing Left","👈"],
"lets_go":["Grinning Face with Fingers on Cheeks","👉‍😁‍👈"],
"mechanical_arm":["Face with Mechanical Arm","🦾"],
"middle_finger":["Face with Middle Finger Up","🖕"],
"nose_punch":["Face Getting Nose Punched","🤥‍🤛"],
"okay_hand":["Face with Okay Hand","👌"],
"phone":["Face on Cellphone","😶‍📱"],
"pinch":["Face Pinching","🤏"],
"ping":["Face with 1 Ping","😠‍1️⃣"],
"pings":["Face with 99 Pings","😡‍9️⃣‍9️⃣"],
"pink":["Pink Smiling Face","🟣‍🙂"],
"pleading_hands":["Pleading Face with Hands Out","🥺‍🤲"],
"plus_eyes":["Face with Plus Eyes","➕‍➖‍➕"],
"pray_halo":["Praying Faco with Halo","😇‍🙏"],
"pray":["Praying Face","🙏"],
"punch_l":["Face Punching Leftwards","🤛‍😠"],
"punch_r":["Face Punching Rightwards","😠‍🤜"],
"punch":["Face Punching Forward","👊‍😠"],
"R74n":["R74n Logo","R74n"],
"raise_fist":["Face Raising Fist","✊"],
"raise_hand":["Face Raising Hand","🖐"],
"raise_the_roof":["Face with Palms Upwards","🙌"],
"raspberry_blow":["Face Blowing Raspberry","😝‍💦"],
"right_down":["Face Pointing Down Right","↘️"],
"right_up":["Face Pointing Up Right","↗️"],
"right":["Face Pointing Right","➡️"],
"rock_on_emo":["Emo Face with Rock On Gesture","🤘‍😔"],
"rock_on":["Face with Rock On Gesture","🤘"],
"sad_wave":["Sad Face Waving","👋‍😞"],
"salami":["Slice of Salami","🥩‍🔴"],
"selfie":["Face Taking Selfie","🤳"],
"shaka":["Face with Call Me Hand","🤙"],
"shocked_clap":["Surprised Face Clapping","👏‍😲"],
"sick_wink":["Face Faking Thermometer Reading","😉‍🌡"],
"spit":["Face Spitting","😙‍💦"],
"superhero":["Superhero","🦸‍♂️"],
"superheroine":["Superheroine","🦸‍♀️"],
"superperson":["Superperson","🦸"],
"supervillain":["Supervillain","🦹"],
"suspicious_fingers":["Suspicious Face Touching Fingers",">.>👉‍👈"],
"thanks":["Happy Face with Folded Hands","☺️🙏"],
"thought_bubble":["Face with Thought Bubble","🤔‍💭"],
"thumbs_down":["Face with Thumbs Down","👎"],
"thumbs_up":["Face with Thumbs Up","👍"],
"up_down":["Face Pointing Up and Down","👆‍👇"],
"up":["Face Pointing Up","👆"],
"vr_headset":["Face Wearing VR Headset","[VR]"],
"watch":["Face Looking at Watch","⌚️"],
"wave":["Face Waving Hello","👋"],
"writing":["Face Writing","✍️"],
"zombie":["Zombie","🧟"],
"zombie2":["Zombie (Yellow)","🧟‍🟡"],
"actually":["Nerd Actually","🤓‍☝️"],
"axe_in_head":["Axe in Head","😵‍🪓"],
"axe":["Face with Axe","🪓‍🙂"],
"black_heart_eyes":["Black Heart Eyes","😍‍🖤"],
"bloodshot_grab":["Grabbing with Bloodshot Eyes","😀‍👁‍👁‍🖐"],
"blue_heart_eyes":["Blue Heart Eyes","😍‍💙"],
"call_me":["Face Gesturing Call Me","🤙"],
"camera_flash":["Taking a Picture","📸"],
"camera":["Face with Camera","📷"],
"caret_eyes":["Caret Eyes Emoticon","^_^"],
"cheers_l":["Cheers (Left)","🙂‍🥂"],
"cheers_r":["Cheers (Right)","🥂‍🙂"],
"chug":["Chugging Beer","😮‍🍺"],
"clown_nose":["Face with Clown Nose","🙂‍🔴"],
"cookie_bit":["Bit Cookie","🍪‍➖"],
"cookie_face":["Cookie Face","🍪‍🙂"],
"cookie":["Cookie","🍪"],
"cube_face":["Cube Face",""],
"devil":["Devil",""],
"diamond_face":["Diamond Face","🔶‍🙂"],
"eye_point":["Face Pointing to Eyes","😐‍✌️"],
"finger_gun_to_head":["Finger Gun to Head","😔‍👈"],
"fist_pump":["Fist Pump","😆‍✊"],
"five_fingers":["Face Holding Up 5 Fingers","✋‍5️"],
"floating_flames":["Face with Floating Flames","😏‍🔥‍🔥‍🔥"],
"floating_rainbow_heart":["Face with Rainbow Heart","☺️‍❤️‍🌈"],
"four_fingers":["Face Holding Up 4 Fingers","✋‍4️"],
"frankenstein":["Frankenstein's Monster","🧟‍🔩"],
"ghost":["Ghost","👻"],
"hand_fanning":["Fanning Hand","🥵‍👋"],
"hand_flap":["Flapping Hands","👋‍☺️‍👋"],
"hands_up":["Hands Up","✋‍😧‍✋"],
"hands":["Showing Hands","✋‍🙂‍✋"],
"hashtag_eyes":["Face with Hashtag Eyes","#️‍➖‍#️"],
"headpat":["Headpatting",""],
"hush_wink":["Hushing Winking Face",""],
"life_jacket":["Face with Life Jacker",""],
"lime_heart_eyes":["Lime Heart Eyes",""],
"lipstick":["Applying Lipstick",""],
"maybe":["Face with Maybe Sign",""],
"middle_finger_smile":["Middle Finger Smile",""],
"nail_biting":["Face Biting Nails",""],
"no":["Face with No Sign","❌"],
"nurse":["Nurse","🧑‍⚕️"],
"octagon_face":["Octagon Face",""],
"old_man":["Old Man","👴"],
"old_person":["Old Person","🧓"],
"old_woman":["Old Woman","👵"],
"one_finger":["Face Holding Up 1 Finger","☝️"],
"orange_heart_eyes":["Orange Heart Eyes",""],
"peace_blush":["Blushing Face with Peace Hand",""],
"peace_sob":["Sobbing Face with Peace Hand",""],
"peace_simple":["Face with Peace Hand",""],
"pied":["Face Hit with Pie",""],
"plague_doctor":["Plague Doctor Mask",""],
"purple_heart_eyes":["Purple Heart Eyes",""],
"rainbow_hearts":["Face with Rainbow Hearts",""],
"rainbow_lips":["Face with Rainbow Lips",""],
"rainbow_vomit":["Face Vomiting Rainbows",""],
"red_glasses":["Face with Red Glasses",""],
"rounded_square_face":["Rounded Square Face",""],
"sad_hand":["Talk to the Hand (Sad)",""],
"sheesh":["Sheesh Face",""],
"short":["Short Face",""],
"shrug":["Shrugging Face",""],
"shutter_shades":["Face with Red Shutter Shades",""],
"shy_hand":["Shy Face with Hand",""],
"snorkel":["Face with Snorkel",""],
"square_face":["Square Face","🟨‍🙂"],
"steering_wheel":["Face Driving",""],
"sunglasses_pull":["Peeking Over Sunglasses",""],
"sunscreen":["Face with Sunscreen",""],
"sweat_wipe":["Wiping Sweat off Face",""],
"talk_to_the_hand":["Talk to the Hand","😐‍✋"],
"tall":["Tall Face",""],
"three_fingers":["Face Holding Up 3 Fingers",""],
"thumbs_ups":["Face with 2 Thumbs Up","👍👍"],
"tone6":["tone6",""],
"triangle_face":["Triangle Face",""],
"tu_shrug":["Tu Shrug Emoticon","¯\\_(ツ)_/¯"],
"two_fingers":["Face Holding Up 2 Fingers",""],
"vaccination":["Face Receiving Vaccine",""],
"vaccine":["Nurse with Vaccine","💉"],
"whiskers":["Face with Whiskers",""],
"white_heart_eyes":["White Heart Eyes",""],
"wink_imp":["Winking Imp",""],
"witch_hat":["Face with Witch Hat","🧙"],
"witch":["Witch","🧙‍♀️"],
"wizard":["Wizard","🧙‍♂️"],
"x_arms":["Face with X Arms","🙅"],
"yellow_heart_eyes":["Yellow Heart Eyes",""],
"yes":["Face with Yes Sign","✅"],
"adult_adult_child_child_child":["2 Adults with 3 Children","🧑‍🧑‍🧒‍🧒‍🧒"],
"adult_adult_child_child":["2 Adults with 2 Children","🧑‍🧑‍🧒‍🧒"],
"adult_adult_child":["2 Adults with Child","🧑‍🧑‍🧒"],
"adult_baby":["Adult with Baby","🧑‍👶"],
"adult_child_child_child":["Adult with Children","🧑‍🧒‍🧒‍🧒"],
"adult_child_child":["Adult with Children","🧑‍🧒‍🧒"],
"adult_child":["Adult with Child","🧑‍🧒"],
"alarm_clock":["alarm_clock","⏰"],
"angry_love":["angry_love",""],
"arms_crossed":["arms_crossed",""],
"baby_bottle":["baby_bottle","🍼"],
"birthday_cake":["birthday_cake","🎂"],
"blissymbolics":["blissymbolics",""],
"bowing":["bowing",""],
"boxing":["boxing","🥊‍😠"],
"bracing":["bracing",""],
"bunny_ear_fingers":["bunny_ear_fingers",""],
"burger":["burger","🍔"],
"calling":["calling",""],
"cat_facepalm":["cat_facepalm","🐱‍🤦"],
"cat_neutral":["cat_neutral","🐱‍😐"],
"cat_puke":["cat_puke","🐱‍🤮"],
"cheek_kiss":["cheek_kiss",""],
"couple_kissing":["couple_kissing","💏"],
"couple_with_heart":["couple_with_heart","💑"],
"dancing":["dancing","🕺"],
"double_flex":["double_flex","💪‍😤‍💪"],
"double_middle_finger":["double_middle_finger",""],
"elf_hat":["elf_hat",""],
"elf":["elf","🧝"],
"fairy_wings":["fairy_wings",""],
"fairy":["fairy","🧚"],
"feeding_baby":["feeding_baby","🧑‍🍼"],
"flying_money":["flying_money","💸"],
"frothing":["frothing",""],
"ghost_blue":["ghost_blue","👻‍🟦"],
"ghost_cyan":["ghost_cyan",""],
"ghost_orange":["ghost_orange","👻‍🟧"],
"ghost_pink":["ghost_pink","👻💖"],
"ghost_red":["ghost_red","👻‍🟥"],
"ghost_yellow":["ghost_yellow","👻‍🟨"],
"goggles":["goggles","🥽"],
"green_top_hat":["green_top_hat","🎩‍🟩"],
"grim_reaper":["grim_reaper",""],
"gun":["gun","🔫"],
"gunpoint":["gunpoint","😨‍🔫"],
"hair_short":["hair_short","👨"],
"haircut":["haircut","💇"],
"hairflip":["hairflip",""],
"heart_eyes_sweating":["heart_eyes_sweating","😍‍🥵"],
"henohenomoheji":["henohenomoheji",""],
"high_tech_worker":["high_tech_worker",""],
"hungover":["hungover",""],
"info_desk":["info_desk","💁"],
"kick_me":["kick_me",""],
"laying_down":["laying_down","🛌"],
"leprechaun_hat":["leprechaun_hat","🎩‍☘️"],
"leprechaun":["leprechaun","🧝‍☘️"],
"massage":["massage","💆"],
"mirror":["mirror","🪞"],
"mohawk_black":["mohawk_black",""],
"nurse_masked":["nurse_masked",""],
"one_baby":["1 Baby","👶"],
"one_child":["1 Child","🧒"],
"one_person":["1 Person","🧍"],
"painting_nails":["painting_nails","💅"],
"pilgrim":["pilgrim",""],
"postal_mark_face":["postal_mark_face","〠"],
"propeller_hat":["propeller_hat",""],
"raining_money":["raining_money","😁‍💵‍💵‍💵"],
"raining":["raining","🌧"],
"reading_sleeping":["reading_sleeping","😴‍📖"],
"reading":["reading","📖"],
"scar":["scar",""],
"scissors":["scissors","✂️"],
"scream_mask":["scream_mask",""],
"shivering":["shivering",""],
"shower_cap":["shower_cap","🙂‍🚿"],
"signing":["signing",""],
"simp":["simp",""],
"sleeping_through_alarm":["sleeping_through_alarm",""],
"smell_no_evil":["smell_no_evil","🙊‍👃"],
"sob_baby":["sob_baby","👶‍😭"],
"squirt_gun":["squirt_gun","🔫‍💦"],
"stop_hand":["stop_hand","😠‍✋"],
"suicide":["suicide","😔‍🔫"],
"telephone_calling":["telephone_calling","🙂‍📞"],
"tete_a_toto":["tete_a_toto",""],
"three_children":["3 Children","🧒‍🧒‍🧒"],
"tiny_head":["tiny_head",""],
"top_hat_monocle":["top_hat_monocle","🧐‍🎩"],
"top_hat":["top_hat","🎩"],
"trident":["trident","🙂‍🔱"],
"triplets":["Triplets","👶‍👶‍👶"],
"twins":["Twins","👶‍👶"],
"two_children":["2 Children","🧒‍🧒"],
"two_people":["2 People","🧑‍🧑"],
"uncle_sam":["uncle_sam",""],
"unicorn_horn":["unicorn_horn",""],
"wand":["wand","🪄"],
"x_hands":["x_hands","🙅"],
"all_seeing":["all_seeing","👁️‍👁️‍👁️‍👁️"],
"angry_horns":["angry_horns","👿‍🟨"],
"artist":["artist","🧑‍🎨"],
"be_not_afraid":["be_not_afraid","👁️‍👼‍👁️"],
"bipolar":["bipolar","😌‍😔"],
"bloodshot_flushed":["bloodshot_flushed","😳‍🩸"],
"bunny_ears":["bunny_ears","🙂‍🐰"],
"calculator":["calculator","🧮"],
"camera_hands":["camera_hands","😉‍👉‍👈"],
"cat_blep":["cat_blep","🐱‍👅"],
"cat_sunglasses":["cat_sunglasses","🐱‍🕶️"],
"character_swap":["character_swap",""],
"cheek_pinch":["cheek_pinch",""],
"coffee":["coffee","☕️"],
"cop_pig":["cop_pig","🐷‍👮"],
"cop":["cop","👮"],
"crossed_out":["crossed_out","🙁‍❌"],
"cyborg":["cyborg","🙂‍🤖"],
"detective_hat":["detective_hat",""],
"detective":["detective","🕵️"],
"dither":["dither",""],
"dogecoin_eyes":["dogecoin_eyes",""],
"emoji_eyes":["emoji_eyes","🟡‍👀"],
"ethereum_eyes":["ethereum_eyes",""],
"evil_horns":["evil_horns","😈‍🟨"],
"factory_worker":["factory_worker","🧑‍🏭"],
"farmer":["farmer","🧑‍🌾"],
"feels":["feels","😭‍🙂"],
"fight_hands":["fight_hands","😠‍🤜‍✋"],
"firefighter_helmet":["firefighter_helmet",""],
"firefighter":["firefighter","🧑‍🚒"],
"greed":["greed",""],
"hair_long_2":["hair_long_2","👧"],
"hair_long_3":["hair_long_3","👱‍♀️"],
"hair_long_4":["hair_long_4",""],
"hair_long_curly":["hair_long_curly","👩‍🦱"],
"hair_long":["hair_long","👩"],
"hair_medium_2":["hair_medium_2","🧒"],
"hair_medium_3":["hair_medium_3",""],
"hair_medium_curly":["hair_medium_curly","🧑‍🦱"],
"hair_medium":["hair_medium","🧑"],
"hair_short_2":["hair_short_2","👦"],
"hair_short_curly":["hair_short_curly","👨‍🦱"],
"half_bottom_left":["half_bottom_left",""],
"half_bottom_right":["half_bottom_right",""],
"half_bottom":["half_bottom",""],
"half_left":["half_left",""],
"half_right":["half_right",""],
"half_top_left":["half_top_left",""],
"half_top_right":["half_top_right",""],
"half_top":["half_top",""],
"hand_eye":["hand_eye","✋‍👁️"],
"hand_kiss":["hand_kiss","😘‍🫴"],
"hard_hat":["hard_hat",""],
"head_scratch":["head_scratch",""],
"headache":["headache","😣‍💢"],
"heh":["heh",""],
"laser_eyes":["laser_eyes",""],
"lego":["lego",""],
"lflgldfglfd":["lflgldfglfd","🔴‍👁️‍🗨️‍👁️‍🗨️"],
"maid_outfit":["maid_outfit",""],
"maid":["maid",""],
"missing_teeth":["missing_teeth",""],
"nazar_eyes":["nazar_eyes","🙂‍🧿‍🧿"],
"nose_pick":["nose_pick","👃‍👆"],
"paper":["paper","📄"],
"picardia":["picardia","😎‍👍"],
"pilot":["pilot","🧑‍✈️"],
"popcorn":["popcorn","🍿"],
"powercry_bow":["powercry_bow","🥺‍🎀"],
"powercry_shy":["powercry_shy","🥺‍🥺"],
"pyromancy":["pyromancy",""],
"rockstar":["rockstar","🧑‍🎤"],
"royal_guard":["royal_guard","💂"],
"sans":["sans","💀‍🔵"],
"scientist":["scientist","🧑‍🔬"],
"shadow_eyes":["shadow_eyes",""],
"shadowy":["shadowy",""],
"simple_smile":["simple_smile","🙂"],
"skull_crossbones":["skull_crossbones","☠️"],
"slime":["slime",""],
"sneeze":["sneeze","🤧‍💦"],
"snowing":["snowing","🥶‍❄️"],
"spider":["spider","🕷️"],
"stickman_head":["stickman_head","⭕️‍⬛️"],
"straw_hat":["straw_hat",""],
"teacher":["teacher","🧑‍🏫"],
"three_eyes":["three_eyes","🙂‍👁️"],
"three_finger_salute":["three_finger_salute",""],
"time_out":["time_out",""],
"tinfoil_hat":["tinfoil_hat",""],
"top_left_bottom_right":["top_left_bottom_right",""],
"top_right_bottom_left":["top_right_bottom_left",""],
"umbrella_raining":["umbrella_raining","☔️"],
"umbrella":["umbrella","☂️"],
"witness_eyes":["witness_eyes",""],
"wrench":["wrench","🔧"],
"x3":["x3","x3"],
"air_force_commander":["air_force_commander","🧑‍✈️‍🧑‍✈️"],
"angry_facebook":["angry_facebook","😠‍😡"],
"arrow_circle_face":["arrow_circle_face",""],
"astronaut":["astronaut","🧑‍🚀"],
"beard":["Bearded Face","🧔"],
"blob_smile":["blob_smile",""],
"blue_cap":["blue_cap","🧢"],
"bodyguard":["bodyguard",""],
"bowler_hat":["bowler_hat",""],
"butcher_knife":["butcher_knife",""],
"captain":["captain","🧑‍✈️"],
"caveman_angry":["caveman_angry",""],
"choccy_milk":["choccy_milk","🥛‍🍫"],
"clapper":["clapper","🎬"],
"coach":["coach",""],
"construction_worker":["construction_worker","👷"],
"crying_blood":["crying_blood","😢‍🩸"],
"cucumber_mask":["cucumber_mask","😴‍🥒"],
"customer_support":["customer_support",""],
"cylinder_face":["cylinder_face",""],
"defeated":["defeated",""],
"drama_mask_happy":["drama_mask_happy",""],
"drama_mask_sad":["drama_mask_sad",""],
"fencer":["fencer","🤺"],
"fez":["fez",""],
"fitness_trainor":["fitness_trainor",""],
"flight_attendant":["flight_attendant",""],
"fortune_teller":["fortune_teller","👳‍♀️‍🔮"],
"genie":["genie","🧞"],
"goatee":["goatee",""],
"graduate":["graduate","🧑‍🎓"],
"gua_pi_mao":["gua_pi_mao","👲"],
"hairdresser":["hairdresser",""],
"headband":["headband",""],
"heart_sunglasses":["heart_sunglasses","😎‍🖤‍🖤"],
"hexagon_face":["hexagon_face",""],
"hijab":["hijab","🧕"],
"hippie_headband":["hippie_headband",""],
"hogchamp":["hogchamp","🐷‍😲"],
"hunter":["hunter",""],
"irritated":["irritated",""],
"jailed":["jailed",""],
"judge":["judge","🧑‍⚖️"],
"juggler":["juggler","🤹"],
"lumberjack_hat":["lumberjack_hat",""],
"lumberjack":["lumberjack",""],
"magician":["magician","🧙‍🪄"],
"masquerade":["masquerade",""],
"mechanic":["mechanic","🧑‍🔧"],
"mime":["mime",""],
"mummy":["mummy","🧟‍🧻"],
"mustache_brown":["mustache_brown",""],
"necromancer":["necromancer","🧙‍💀"],
"npc":["npc",""],
"orange_cap":["orange_cap","🧢‍🟧"],
"parallelogram_face":["parallelogram_face",""],
"pentagon_face":["pentagon_face",""],
"pharaoh":["pharaoh",""],
"pill":["pill",""],
"polandball":["polandball","🙂‍🇵🇱"],
"postman":["postman",""],
"rain_hat":["rain_hat",""],
"rainbow_bandana":["rainbow_bandana",""],
"rate1":["rate1",""],
"rate2":["rate2",""],
"rate3":["rate3",""],
"rate4":["rate4",""],
"rate5":["rate5",""],
"red_cap":["red_cap","🧢‍🟥"],
"referee":["referee",""],
"rescue_worker":["rescue_worker","⛑️"],
"rifle":["rifle",""],
"right_triangle_face":["right_triangle_face",""],
"sailor":["sailor","🙂‍⛵️"],
"secret_agent":["secret_agent",""],
"security_guard":["security_guard",""],
"snowboarder":["snowboarder","🏂"],
"sobbing_blood":["sobbing_blood","😭‍🩸"],
"sobbing_hands":["sobbing_hands",""],
"soccer_ball_eyes":["soccer_ball_eyes",""],
"soldier":["soldier","🙂‍🪖"],
"sombrero":["sombrero",""],
"sprout":["sprout","🙂‍🌱"],
//"stubble_old":["stubble_old",""],
"tilde_eyes":["tilde_eyes","~_~"],
"toasted":["toasted","⚫️‍👁️‍👁️‍🔥"],
"top_hat_sunglasses":["top_hat_sunglasses","😎‍🎩"],
"trapezoid_face":["trapezoid_face",""],
"tripping":["tripping",""],
"turban":["turban","👳"],
"ushanka":["ushanka",""],
"veil":["veil","👰"],
"womans_hat":["womans_hat","🙂‍👒"],
"hair_long5":["hair_long5",""],
"rasta":["rasta",""],
"censored":["censored",""],
"wings":["wings","🙂‍🕊️"],
"angel":["angel","😇‍🕊️"],
"angelthump":["angelthump","😇‍🕊️‍🥺"],
"knight":["knight",""],
"knife":["knife","🔪"],
"stabbed":["stabbed","🔪‍😵"],
"pope":["pope","🙂‍🇻🇦"],
"pointing_laughing":["pointing_laughing","👈‍😆"],
"whisper":["whisper",""],
"blending":["blending",""],
"venn_diagram":["venn_diagram",""],
"blue_tongue":["blue_tongue","😛‍🟦"],
"nasal_cannula":["nasal_cannula",""],
"meditating":["meditating","🧘"],
"hazmat_suit":["hazmat_suit",""],
"fedora":["fedora",""],
//R74moji 13:
"viking":["viking",""],
"binoculars":["binoculars",""],
"keffiyeh":["keffiyeh",""],
"slot_eyes":["slot_eyes",""],
"guy_fawkes":["guy_fawkes",""],
"conical_hat":["conical_hat",""],
"diving_helmet":["diving_helmet",""],
"bride_groom":["bride_groom","👰‍🤵"],
"groom_groom":["groom_groom","🤵‍🤵"],
"bride_bride":["bride_bride","👰‍👰"],
"carpenter":["carpenter",""],
"milkman":["milkman",""],
"anubis":["anubis",""],
"gnome":["gnome",""],
"angel_baby":["angel_baby","👼"],
"dog":["dog","🐶"],
"dog_wink":["dog_wink","🐶‍😉"],
"dog_shocked":["dog_shocked","🐶‍😲"],
"dog_love":["dog_love","🐶‍😍"],
"dog_angry":["dog_angry","🐶‍😠"],
"dog_sad":["dog_sad","🐶‍😞"],
"dog_flushed":["dog_flushed","🐶‍😳"],
"frog":["frog","🐸"],
"ski_helmet":["ski_helmet","⛷️"],
"football_helmet":["football_helmet","🙂‍🏈"],
"eye_black":["eye_black",""],
"america_face_paint":["america_face_paint","🙂‍🇺🇸"],
"archer":["archer","😉‍🏹"],
"white_cap":["white_cap",""],
"baseball":["baseball","🙂‍⚾️"],
"basketball":["basketball","⛹️"],
"cyan_ball":["cyan_ball",""],
"soccer":["soccer","🙂‍⚽️"],
"volleyball":["volleyball","🙂‍🏐"],
"white_ball":["white_ball",""],
"beachball":["beachball",""],
"cat_hacker":["cat_hacker","🐱‍💻"],
"cat_astronaut":["cat_astronaut","🐱‍🚀"],
"cat_hipster":["cat_hipster","🐱‍👓"],
"two_white_dots_face":["two_white_dots_face","⚉"],
"two_black_dots_face":["two_black_dots_face","⚇"],
"two_dots_face":["two_dots_face","⚇‍🟨"],
"neutral_tongue":["neutral_tongue","😐‍👅"],
"rainbow":["rainbow","😁‍🌈"],
"thinkception":["thinkception","🤔‍🤔‍🤔‍🤔"],
"100_eyes":["100_eyes","😄‍💯‍💯"],
"pathological_liar":["pathological_liar",""],
"double_masked":["double_masked",""],
"sob_relieved":["sob_relieved","😭‍😌"],
"sob_smile":["sob_smile","😭‍🙂"],
"sob_evil":["sob_evil","😭‍😈"],
"sob_cool":["sob_cool","😭‍😎"],
"sob_vomiting":["sob_vomiting","😭‍🤮"],
"one_tooth":["one_tooth",""],
"crewmate":["crewmate","ඞ"],
"imposter":["imposter",""],
"imposter_hush":["imposter_hush","🤫‍ඞ"],
"amogus":["amogus",""],
"evil_hush":["evil_hush",""],
"dented":["dented",""],
"octopus":["octopus","🐙"],
"octopus_gentleman":["octopus_gentleman","🐙‍🧐‍🎩"],
"troll_face":["troll_face",":tf:"],
"chart_up":["chart_up",""],
"chart_down":["chart_down",""],
"laptop_weary":["laptop_weary","😩‍💻"],
"nasal_swab":["nasal_swab",""],
"iv":["iv",""],
"point_self":["point_self","😮‍👈"],
"seatbelt":["seatbelt",""],
"surgeon":["surgeon","🧑‍⚕️"],
"sun":["sun","☀️"],
"sun_face":["sun_face","🌞"],
"lit_moon":["lit_moon","🌕"],
"lit_moon_face":["lit_moon_face","🌝"],
"waning_crescent_moon":["waning_crescent_moon","🌘"],
"waxing_crescent_moon":["waxing_crescent_moon","🌒"],
"waning_crescent_moon_face":["waning_crescent_moon_face","🌜"],
"waxing_crescent_moon_face":["waxing_crescent_moon_face","🌛"],
"exploding_head_angry":["exploding_head_angry","🤯‍😠"],

//R74moji 14:
"imposter_accuse":["imposter_accuse",""],
"frog_hat":["frog_hat",""],
"miner":["miner",""],
"golf_flag":["golf_flag",""],
"lava_slime":["lava_slime",""],
"golden_egg":["golden_egg",""],
"red_egg":["red_egg",""],
"orange_egg":["orange_egg",""],
"yellow_egg":["yellow_egg",""],
"lime_egg":["lime_egg",""],
"green_egg":["green_egg",""],
"blue_egg":["blue_egg",""],
"cyan_egg":["cyan_egg",""],
"purple_egg":["purple_egg",""],
"brown_egg":["brown_egg",""],
"gray_egg":["gray_egg",""],
"pink_egg":["pink_egg",""],
"black_egg":["black_egg",""],
"easter_egg":["easter_egg",""],
"corner":["corner",""],
"cheese":["cheese","🧀"],
"cheese_face":["cheese_face",""],
"poo":["poo",""],
"poo_face":["poo_face","💩"],
"sad_poo":["sad_poo",""],
"gingerbread_man":["gingerbread_man",""],
"incomplete":["incomplete",""],
"fig_leaf":["fig_leaf",""],
"falling_leaves":["falling_leaves",""],
"autumn":["autumn",""],
"leaf_eyes":["leaf_eyes",""],
"broke":["broke",""],
"spicy":["spicy",""],
"crying_poo":["crying_poo",""],
"pink_poo":["pink_poo",""],
"green_poo":["green_poo",""],
"wait":["wait",""],
"no_face":["no_face",""],
"ko_face":["ko_face",""],
"yo_face":["yo_face",""],
"go_face":["go_face",""],
"on_face":["on_face",""],
"wolf":["wolf","🐺"],
"arctic_wolf":["arctic_wolf",""],
"shaking":["shaking","🫨"],
"werewolf":["werewolf",""],
"cheese_moon":["cheese_moon",""],
"button_push":["button_push",""],
"gardener":["gardener",""],
"anthomania":["anthomania",""],
"add_contact":["add_contact",""],
"remove_contact":["remove_contact",""],
"delivery_person":["delivery_person",""],
"bindle":["bindle",""],
"snowman_snowing":["snowman_snowing",""],
"french":["french",""],
"face_mask_glasses":["face_mask_glasses",""],
"nda":["nda",""],
"slam":["slam",""],
"masked_hog":["masked_hog",""],
"martial_artist":["martial_artist",""],
"cheerleader":["cheerleader",""],
"sparrer":["sparrer",""],
"sniff":["sniff",""],
"italic":["italic",""],
"bold":["bold",""],
"underline":["underline",""],
"strikethrough":["strikethrough",""],
"strikethrough_sad":["strikethrough_sad",""],
"hyperlink_magenta":["hyperlink_magenta",""],
"hyperlink":["hyperlink",""],
"hyperlink_visited":["hyperlink_visited",""],
"selection":["selection",""],
"highlight":["highlight",""],
"serif":["serif",""],
"inverted":["inverted",""],
"princess":["princess","👸"],
"prince":["prince","🤴"],
"screaming_crying":["screaming_crying",""],
"batman":["batman",""],
"bear":["bear",""],
"being_drawn":["being_drawn",""],
"bits":["bits",""],
"black_bear":["black_bear",""],
"black_eye":["black_eye",""],
"blah_blah_blah":["blah_blah_blah",""],
"blind":["blind",""],
"bricked":["bricked",""],
"bullet_user":["bullet_user",""],
"burbling":["burbling",""],
"car_face":["car_face",""],
"carved_pumpkin":["carved_pumpkin",""],
"cat_facepalm":["cat_facepalm",""],
"cat_scream":["cat_scream",""],
"chick":["chick",""],
"chicken":["chicken",""],
"cracked_egg":["cracked_egg",""],
"dancing2":["dancing2",""],
"dnd":["dnd",""],
"domino_mask":["domino_mask",""],
"dropped_eyes":["dropped_eyes",""],
"eggshell":["eggshell",""],
"entering":["entering",""],
"exiting":["exiting",""],
"fire":["fire",""],
"gear":["gear",""],
"group_add":["group_add",""],
"group_edit":["group_edit",""],
"group_remove":["group_remove",""],
"group":["group",""],
"hair_long_ribbons":["hair_long_ribbons",""],
"hanging_eyes":["hanging_eyes",""],
"harry_potter":["harry_potter",""],
"hatching_chick":["hatching_chick",""],
"hatching_person":["hatching_person",""],
"holding_breath":["holding_breath",""],
"house_face":["house_face",""],
"incense":["incense",""],
"jack_o_lantern":["jack_o_lantern",""],
"japanese_headband":["japanese_headband",""],
"juice":["juice",""],
"just_eyes":["just_eyes",""],
"just_face":["just_face",""],
"laptop_parenting":["laptop_parenting",""],
"laptop2":["laptop2",""],
"leftwards_hand":["leftwards_hand",""],
"lightswitch":["lightswitch",""],
"lollipop":["lollipop",""],
"mail_empty":["mail_empty",""],
"mail_forward":["mail_forward",""],
"mail_open":["mail_open",""],
"mail_reply":["mail_reply",""],
"mail_send":["mail_send",""],
"mail":["mail",""],
"multitask_book":["multitask_book",""],
"multitask":["multitask",""],
"neck_gaiter":["neck_gaiter",""],
"odor_be_gone":["odor_be_gone",""],
"ok_arms":["ok_arms",""],
"omegalul":["omegalul",""],
"ornament_face":["ornament_face",""],
"panda":["panda",""],
"pencil":["pencil",""],
"picking_flower":["picking_flower",""],
"piercings":["piercings",""],
"piggy_bank":["piggy_bank",""],
"polar_bear":["polar_bear",""],
"pole_lick":["pole_lick",""],
"police_car_face":["police_car_face",""],
"pompous":["pompous",""],
"pretty":["pretty",""],
"pumpkin_costume":["pumpkin_costume",""],
"pumpkin":["pumpkin",""],
"R74n":["R74n",""],
"red_eyes":["red_eyes",""],
"red_flag":["red_flag",""],
"reverse_card":["reverse_card",""],
"rightwards_hand":["rightwards_hand",""],
"rocket":["rocket",""],
"santa_joy":["santa_joy",""],
"smirk2":["smirk2",""],
"spider_man":["spider_man",""],
"streamer_mode":["streamer_mode",""],
"sunburn":["sunburn",""],
"swimmer":["swimmer",""],
"tableflip":["tableflip",""],
"unflip":["unflip",""],
"waiting":["waiting",""],
"xray":["xray",""],

//"":["",""]
}
/*    format list from file names
l = "".split(".png");
a = "";
for (var i in l) {
  a += '"'+l[i]+'":["'+l[i]+'",""],\n'
}
console.log(a)
*/

/*    generate viewer links
a = "";
k = Object.keys(R74mojiData);
for (var i in k) {
  var name = k[i];
  a += "https://r74n.com/moji/view?"+name+"\n"
}
console.log(a)
*/

ValidR74mojiAttributes = ["type"]

function createPlaceholder() {/*https://stackoverflow.com/a/7004837/8234438*/
  var img = document.createElement('img');
  img.setAttribute('style', 'width:100%;height:100%;border:none;display:block');
  img.src = 'data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==';
  return img;
}

function drawImageScaled(img, ctx) {
  var canvas = ctx.canvas ;
  var hRatio = canvas.width  / img.width    ;
  var vRatio =  canvas.height / img.height  ;
  var ratio  = Math.min ( hRatio, vRatio );
  var centerShift_x = ( canvas.width - img.width*ratio ) / 2;
  var centerShift_y = ( canvas.height - img.height*ratio ) / 2;  
  ctx.clearRect(0,0,canvas.width, canvas.height);
  ctx.drawImage(img, 0,0, img.width, img.height,
                     centerShift_x,centerShift_y,img.width*ratio, img.height*ratio);  
}

window.addEventListener("load",function(){
  var EmojiTagList = document.getElementsByTagName("emoji");
  var EmojiNum = 0;
  if (EmojiTagList.length > 0) {
    var style = document.createElement('style');
    style.type = 'text/css';
    style.innerHTML = '.R74mojiClass {image-rendering:optimizeSpeed;image-rendering:-moz-crisp-edges;image-rendering:-o-crisp-edges;image-rendering: -webkit-optimize-contrast;image-rendering:pixelated;image-rendering:optimize-contrast;-ms-interpolation-mode:nearest-neighbor;}';
    document.getElementsByTagName('head')[0].appendChild(style);
  }
  for (i = 0; i < EmojiTagList.length; ++i) {
    var OriginalEmojiTag = EmojiTagList[i];
    var EmojiTag = document.createElement("canvas");

    for(var n in OriginalEmojiTag.attributes){/*transfer relevant attributes*/
      var k = OriginalEmojiTag.attributes[n];
      if (ValidR74mojiAttributes.includes(k.name)){
        EmojiTag.setAttribute(k.name,OriginalEmojiTag.getAttribute(k.name));
        OriginalEmojiTag.removeAttribute("type");
      }
    }

    OriginalEmojiTag.setAttribute("loaded","true");


    var EmojiType = EmojiTag.getAttribute("type");

    if (!(R74mojiData[EmojiType]==undefined)) {
      var ImageURL = "https://r74n.com/moji/png/"+EmojiType+".png";
      var invalid = false
    }
    else {var ImageURL = "https://r74n.com/moji/png/replacement.png";var invalid=true}
    EmojiTag.setAttribute("src",ImageURL);
    EmojiTag.setAttribute("class","R74mojiImg");
    EmojiTag.style.width = "1.75em";
    EmojiTag.style.height = "1.75em";
    EmojiTag.style.minWidth = "1em";
    EmojiTag.style.minHeight = "1em";
    EmojiTag.style.display = "inline-block";
    EmojiTag.style.verticalAlign = "middle";
    EmojiTag.style.marginBottom = "0.3em";
    EmojiTag.style.cursor = "text";
    if (!(invalid)) {
      EmojiTag.setAttribute("title",R74mojiData[EmojiType][0]);
      if (R74mojiData[EmojiType][1]=="") {
        EmojiTag.setAttribute("alt","[?]");
      }
      else {
        EmojiTag.setAttribute("alt",R74mojiData[EmojiType][1]);
      }
    }
    else {
      EmojiTag.setAttribute("title","Invalid Emoji ("+EmojiType+")");
      EmojiTag.setAttribute("alt","[?]");
    }
    EmojiTag.style.webkitUserDrag = "none";
    EmojiTag.style.userDrag = "none";

    EmojiTag.id = "emoji-"+EmojiNum;
    EmojiNum += 1;
    var ctx = EmojiTag.getContext("2d");
    EmojiTag.setAttribute('width', '480');
    EmojiTag.setAttribute('height', '480');

    //set canvas to image url
    var img = new Image;
    img.crossOrigin = "Anonymous";
    dataOnLoad(img,ctx,ImageURL,EmojiTag);

    OriginalEmojiTag.appendChild(EmojiTag);

  }

})


function dataOnLoad(img2,ctx2,ImageURL2,EmojiTag2){
  img2.onload = function(){
    drawImageScaled(img2,ctx2); // Or at whatever offset you like
  };
  img2.src = ImageURL2;

}